# Generated by Django 4.2.2 on 2023-07-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0005_alter_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='blurb',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='book',
            name='thumbnail',
            field=models.ImageField(upload_to='media'),
        ),
    ]
