# Generated by Django 4.2.2 on 2023-07-01 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0006_alter_book_blurb_alter_book_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='blurb',
            field=models.TextField(),
        ),
    ]
